// `cloudflare-env.d.ts` is regenerated by `wrangler types` from bindings
// declared in `wrangler.jsonc` — it doesn't know about secrets set out of
// band via `wrangler secret put` or `.dev.vars`. Merge those in here so
// they stay typed without hand-editing the generated file (which would be
// overwritten on the next `npm run cf-typegen`).
interface CloudflareEnv {
  ANTHROPIC_API_KEY?: string;
}
